import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('camera success advances the guide without another Next click', async ({ page }) => {
  await page.goto('/');
  await page.locator('#onboarding-next').click();
  await page.locator('[data-onboarding-panel="1"] summary').click();
  await page.locator('#onboarding-skip').click();
  await page.locator('#onboarding-camera').click();
  await expect(page.locator('[data-onboarding-panel="3"]')).toBeVisible({ timeout: 60_000 });
  await page.locator('#onboarding-later').click();
  await page.locator('#camera-toggle').click();
  await expect(page.locator('#camera-status')).toContainText('尚未开启');
});

test('guide footer remains visible, preview stays accessible, and successful selection advances', async ({ page }) => {
  await page.setViewportSize({ width: 860, height: 620 });
  await page.goto('/');
  await page.locator('#onboarding-next').click();
  await expect(page.locator('.character-choices > button')).toHaveCount(3);
  const footer = await page.locator('.onboarding-footer').boundingBox();
  expect(footer.y + footer.height).toBeLessThanOrEqual(620);
  const stage = await page.locator('#stage').boundingBox();
  const guide = await page.locator('#onboarding-dialog').boundingBox();
  expect(stage.x + stage.width).toBeGreaterThan(guide.x + guide.width + 150);
  await page.locator('#load-miao').click();
  await expect(page.locator('#onboarding-model-state')).toContainText('✓ 已载入');
  await expect(page.locator('[data-onboarding-panel="2"]')).toBeVisible();
  await page.locator('#onboarding-body').check();
  await page.reload();
  await page.locator('#onboarding-later').click();
  await expect(page.locator('#body-tracking')).toBeChecked();
});

test('help is in-app, including nested links, and never unloads the scene', async ({ page }) => {
  await page.goto('/'); await page.locator('#onboarding-later').click();
  await page.locator('#quick-miao').click();
  await expect(page.locator('#stage')).toHaveAttribute('data-render-ready', 'true');
  const location = page.url();
  await page.getByRole('link', { name: '查看平台接入步骤与限制' }).click();
  await expect(page.locator('#help-dialog')).toBeVisible();
  await expect(page.frameLocator('#help-frame').locator('h1')).toContainText('平台');
  await page.frameLocator('#help-frame').getByRole('link', { name: '使用帮助', exact: true }).click();
  await expect(page.locator('#help-frame')).toHaveAttribute('src', /help.html$/);
  await page.locator('#help-close').click();
  expect(page.url()).toBe(location);
  await expect(page.locator('#stage')).toHaveAttribute('data-render-ready', 'true');
});

test('creation renders, resumes drafts, saves one library entry, and reimports editable VRM', async ({ page }) => {
  test.setTimeout(180_000);
  await page.goto('/'); await page.locator('#onboarding-later').click();
  await page.locator('#create-character').click();
  await page.locator('#creator-name').fill('榛子猫');
  await page.locator('#creator-next').click();
  await page.getByRole('button', { name: '大头幼猫', exact: true }).click();
  await page.locator('#creator-next').click();
  await page.locator('[data-field="face.eyeShape"]').selectOption('round');
  await page.locator('#creator-next').click();
  await page.locator('#creator-ears').selectOption('folded');
  await expect(page.locator('#creator-status')).toContainText('草稿已保存');
  await page.screenshot({ path: test.info().outputPath('creator-desktop.png') });
  await page.locator('#creator-close').click();
  await page.reload(); await page.locator('#onboarding-later').click();
  await page.locator('#create-character').click();
  await expect(page.locator('#creator-ears')).toHaveValue('folded');
  await page.locator('#creator-save').click();
  await expect(page.locator('#creator-status')).toContainText('已保存到角色库');
  const before = await page.locator('#model-library option').count();
  await page.locator('#creator-save').click();
  await expect(page.locator('#creator-status')).toContainText('已保存到角色库');
  expect(await page.locator('#model-library option').count()).toBe(before);
  const pending = page.waitForEvent('download');
  await page.locator('#creator-export').click();
  const download = await pending;
  expect(download.suggestedFilename()).toBe('榛子猫.vrm');
  const bytes = await readFile(await download.path());
  const doc = JSON.parse(bytes.subarray(20, 20 + bytes.readUInt32LE(12)).toString());
  expect(doc.extras.miaoCharacter.parts.ears).toBe('folded');
  expect(doc.extras.miaoCharacter.face.eyeShape).toBe('round');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: test.info().outputPath('creator-mobile.png') });
  await page.locator('#creator-close').click();
  await page.locator('#model-file').setInputFiles({ name: '榛子猫.vrm', mimeType: 'model/vrm', buffer: bytes });
  await expect(page.locator('#stage')).toHaveAttribute('data-render-ready', 'true');
  await expect(page.locator('#edit-created-character')).toBeEnabled();
  await page.locator('.advanced-settings > summary').click();
  await page.locator('#edit-created-character').click();
  await expect(page.locator('#creator-name')).toHaveValue('榛子猫');
  await page.locator('#creator-next').click();
  await page.locator('#creator-next').click();
  await expect(page.locator('[data-field="face.eyeShape"]')).toHaveValue('round');
  await page.locator('#creator-save').click();
  await expect(page.locator('#creator-status')).toContainText('已保存到角色库');
  const count = await page.locator('#model-library option').count();
  await page.locator('#creator-close').click();
  await page.locator('#edit-created-character').click();
  await page.locator('#creator-name').fill('榛子猫改名');
  await page.locator('#creator-save').click();
  await expect(page.locator('#creator-status')).toContainText('已保存到角色库');
  expect(await page.locator('#model-library option').count()).toBe(count);
  await expect(page.locator('#model-library option:checked')).toContainText('榛子猫改名');
});

test('pixiv material menu contains no English or separate outlines', async ({ page }) => {
  await page.goto('/'); await page.locator('#onboarding-later').click();
  await page.locator('#model-file').setInputFiles('public/examples/pixiv-vrm1.vrm');
  await expect(page.locator('#stage')).toHaveAttribute('data-render-ready', 'true');
  const names = await page.locator('#avatar-material option').allTextContents();
  expect(names.length).toBeGreaterThan(3);
  expect(names.join('')).not.toMatch(/[A-Za-z]/);
  await expect(page.locator('#import-model')).toBeEnabled();
  await page.locator('.studio-settings > summary').click();
  const lastPart = String(names.length - 1);
  await page.locator('#avatar-material').selectOption(lastPart);
  await page.locator('#avatar-color').fill('#ba4d71');
  await page.reload(); await page.locator('#onboarding-later').click();
  await expect(page.locator('#stage')).toHaveAttribute('data-render-ready', 'true');
  await expect(page.locator('#import-model')).toBeEnabled();
  await page.locator('.studio-settings > summary').click();
  await page.locator('#avatar-material').selectOption(lastPart);
  await expect(page.locator('#avatar-color')).toHaveValue('#ba4d71');
});
