cmake_minimum_required(VERSION 3.20)
project(MiaoCamera LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
file(GLOB BASE_SOURCES CONFIGURE_DEPENDS softcam/src/baseclasses/*.cpp)
file(GLOB CORE_SOURCES CONFIGURE_DEPENDS softcam/src/softcamcore/*.cpp)
add_library(softcam SHARED ${BASE_SOURCES} ${CORE_SOURCES} softcam/src/softcam/softcam.cpp softcam/src/softcam/softcam.def)
target_include_directories(softcam PRIVATE softcam/src softcam/src/baseclasses)
target_compile_definitions(softcam PRIVATE UNICODE _UNICODE WIN32 _CRT_SECURE_NO_WARNINGS)
target_link_libraries(softcam PRIVATE strmiids winmm ole32 oleaut32 uuid advapi32 user32 gdi32)
add_executable(camera-register WIN32 register.cpp)
target_link_libraries(camera-register PRIVATE shell32)
target_link_options(camera-register PRIVATE "/MANIFESTUAC:level='requireAdministrator' uiAccess='false'")
add_executable(camera-sender smoke-sender.cpp)
target_include_directories(camera-sender PRIVATE softcam/src)
target_link_libraries(camera-sender PRIVATE softcam)
