export type Background = 'studio' | 'green' | 'transparent';
export type RenderQuality = 'auto' | 'performance' | 'balanced' | 'quality';
export type OutputAspect = 'auto' | '16:9' | '9:16' | '1:1';
export type ViewPreset = 'head' | 'upper' | 'full';
export type AppSettings = { activeModelId: string; background: Background; cameraId: string; bodyTracking: boolean; mirror: boolean; onboardingComplete: boolean; outputAspect: OutputAspect; renderQuality: RenderQuality; sensitivity: number; smoothing: number; viewPreset: ViewPreset };
export type ModelMetrics = { fileBytes: number; triangles: number; materials: number; textures: number; maxTextureSize: number; textureBytes: number; geometryBytes: number };
export const DEFAULT_SETTINGS: Readonly<AppSettings>;
export function parseSettings(raw: string | null): AppSettings;
export function validateModelFile(file: Pick<File, 'name' | 'size'>, maxBytes: number): string;
export { cameraConstraints, cameraErrorMessage, createWithGpuFallback, stopMediaStream } from './capture.mjs';
export function trackingQuality(fps: number, faceVisible: boolean): { label: string; level: 'idle' | 'good' | 'fair' | 'weak'; value: number };
export function scaleMotion<T extends Record<string, number>>(motion: T, sensitivity: number): T;
export function onboardingState(step: number, hasModel: boolean, hasCamera: boolean): { current: number; canContinue: boolean; nextLabel: string; progress: string };
export function renderPixelRatio(quality: RenderQuality, devicePixelRatio?: number): number;
export function estimateModelPerformance(metrics: ModelMetrics): { level: 'good' | 'warning' | 'heavy'; label: string; textureMegabytes: number };
export function createSettingsProfile(settings: AppSettings): { format: 'miao-motion-settings'; version: 2; settings: Pick<AppSettings, 'activeModelId' | 'background' | 'bodyTracking' | 'mirror' | 'outputAspect' | 'renderQuality' | 'sensitivity' | 'smoothing' | 'viewPreset'> };
export function parseSettingsProfile(raw: string): Pick<AppSettings, 'activeModelId' | 'background' | 'bodyTracking' | 'mirror' | 'outputAspect' | 'renderQuality' | 'sensitivity' | 'smoothing' | 'viewPreset'> | null;
export function modelLoadErrorMessage(error: unknown): string;
export function sanitizeDiagnosticMessage(value: unknown): string;
export function coarseUserAgent(userAgent: string): string;
export type DiagnosticEvent = { at: string; kind: string; message: string };
export function parseDiagnosticEvents(raw: string | null, limit?: number): DiagnosticEvent[];
